name: ZeroCore
version: '1.0-SNAPSHOT'
main: kr.hyfata.zero.ZeroCore
api-version: '1.21'
dependencies:
  server:
    ZeroDBCore:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: true
      join-classpath: true